version: '3.7'

services:
  # Node.js services
  producer:
    build: producer
    volumes:
      - ./producer:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  grpc-server:
    build: grpc-server
    volumes:
      - ./grpc-server:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"
      - "50051:50051"
    depends_on:
      - producer

  consumer:
    build: consumer
    volumes:
      - ./consumer:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - producer
      - grpc-server

  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reporting

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
