version: '3.7'

services:
  # Node.js services
  kafka-producer:
    build: kafka-producer
    volumes:
      - ./kafka-producer:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  kafka-consumer-user-search:
    build: kafka-consumer-user-search
    volumes:
      - ./kafka-consumer-user-search:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - kafka-producer

  kafka-consumer-news:
    build: kafka-consumer-news
    volumes:
      - ./kafka-consumer-news:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - kafka-producer

  # Databases
  mongo-user-search:
    image: mongo:4.4.1-bionic
    container_name: mongousers
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reporting

  mongo-news:
    image: mongo:4.4.1-bionic
    container_name: mongonews
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reporting

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
